[package]
name = "pv_recorder"
version = "1.2.5"
edition = "2018"
description = "Rust recorder library for Picovoice"
license = "Apache-2.0"
repository = "https://github.com/Picovoice/pvrecorder"
keywords = [
    "audio",
    "recorder",
]
publish = true
include = [
	".gitignore",
	"build.rs",
	"Cargo.toml",
	"data/",
	"README.md",
	"src/",
]

[lib]
name = "pv_recorder"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
libc = "0.2"
libloading = "0.8"
