name: C Template

inputs:
  pv_recorder_platform:
    required: true
  output_dir:
    required: true
  shell:
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - name: Create build directory
      run: cmake -B ./build -S . -DPV_RECORDER_PLATFORM="${{ inputs.pv_recorder_platform }}" -DOUTPUT_DIR="${{ inputs.output_dir }}"
      working-directory: project
      shell: ${{ inputs.shell }}

    - name: Build
      run: cmake --build ./build
      working-directory: project
      shell: ${{ inputs.shell }}

    - name: Test
      run: ctest --output-on-failure
      working-directory: project/build
      shell: ${{ inputs.shell }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.pv_recorder_platform }}
        path: |
          lib/${{ inputs.output_dir }}/libpv_recorder.*
          lib/node/${{ inputs.output_dir }}/pv_recorder.node
        retention-days: 3
